# Generated by Django 6.0 on 2026-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('home', 'Home Supply'), ('office', 'Office Supply'), ('distributor', 'Distributor')], default='home', max_length=50),
        ),
    ]
